pipeline{
   agent any 
   
   tools{
        maven 'M2_HOME'
   }
   stages{
    stage ("sonar-scan"){
     steps{
            withSonarQubeEnv("SonarQube")
        sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=RGJ2023_geo-app'   
    }
    }
    stage("maven"){
        steps{ 
        sh 'mvn clean validate compile install test package'
        }
    }
    stage('upload artifact'){
        steps{
            sh 'curl -uadmin:APB29Dhy6UpUNdnyKWtfmHidLbN -T target/bio*.jar \
             "http://54.173.45.215:8081/artifactory/geolocation/geo/bio_${BUILD_D}.jar"'
            
        }
    }
   }
}
}

