pipeline{
   agent any 
   
   tools{
        maven 'M2_HOME'
   }
   stages{
    stage("maven"){
        steps{ 
        sh 'mvn clean validate compile install test package'
        }
    }
    stage('upload artifact'){
        steps{
            sh 'curl -uadmin:APB29Dhy6UpUNdnyKWtfmHidLbN -T target/bio*.jar\
             "http://54.173.45.215:8081/artifactory/geolocation/geo/bio_${BUILD.ID}.jar'
        }
    }
   }
}
